artifacts_root : artifacts

data_ingestion:
root_dir : artifacts/data_ingestion
source_url: https://github.com/RajeshB-0699/extracted-zip-files/raw/main/winequality-red.zip
local_data_file: artifacts/data_ingestion/data.zip
unzip_dir: artifacts/data_ingestion